Metrics/AbcSize:
  Exclude:
  - "spec/**/*"
  - "test/**/*"

Metrics/MethodLength:
  Exclude:
  - "spec/**/*"
  - "test/**/*"

Style/Documentation:
  Exclude:
  - "spec/**/*"
  - "test/**/*"
  - "apps/**/*"
  - "controllers/**/*"
  - "main.rb"
  - "models/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
