# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    working_directory: ~/repo

    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        RAILS_ENV: test
        RACK_ENV: test
        POSTGRES_USER: circleci
        PGHOST: 127.0.0.1
        PGUSER: circleci
        # BUNDLE_PATH: vendor/bundle

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: twatter_test
        POSTGRES_PASSWORD: ""

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    # Database setup
    - run:
        name: Setup database
        command: |
          bundle exec rake db:drop db:create db:schema:load --trace
        environment:
          DATABASE_URL: "postgres://circleci@localhost:5432/twatter_test"
          DATABASE_NAME: "twatter_test"

    # run tests!
    - run:
        name: run tests
        command: |
          bundle exec rake
        environment:
          DATABASE_URL: "postgres://circleci@localhost:5432/twatter_test"

