# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    working_directory: ~/repo

    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        DATABASE_URL: "postgres://circleci@localhost:5432/twatter_test"
        PG_HOST: localhost
        PG_USER: circleci
        RACK_ENV: test

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/postgres:9.4
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: twatter_test

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run:
        name: Create and load database schema
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    # run tests!
    - run:
        name: run tests
        command: |
          bundle exec rake

